kind: pipeline
type: docker
name: build

platform:
  os: linux
  arch: amd64

pipeline:
- name: build-fips-unittest
  image: amarburg/lsdslam-dev-host
  commands:
    - ./fips set config linux-make-unittest
    - ./fips build

- name: slack
  image: plugins/slack
  settings:
    webhook:
      from_secret: slack_webhook
  when:
    status: [ success, failure ]
