kind: pipeline
type: docker
name: build

platform:
  os: linux
  arch: amd64

steps:
- name: build-fips-unittest
  image: amarburg/lsdslam-dev-host
  commands:
    - ./fips set config linux-make-unittest
    - ./fips build

## Build with ROS melodic
- name: build-ros-melodic
  image: amarburg/drone-ci-ros-melodic:latest
  commands:
    - wget -O- https://gitlab.com/amarburg/ros_drone_ci/-/raw/master/bootstrap.sh | /bin/bash
  environment:
    ROS_PACKAGES_TO_INSTALL: cv-bridge image-transport opencv-apps
    WSTOOL_RECURSIVE: true

- name: trigger-github-downstream
  image: plugins/downstream
  settings:
    server: https://github.drone.camhd.science
    fork: true
    token:
      from_secret: github_drone_token
    repositories:
      - apl-ocean-engineering/serdp_recorder
      - apl-ocean-engineering/serdp_player

- name: slack
  image: plugins/slack
  settings:
    webhook:
      from_secret: slack_webhook
  when:
    status: [ success, failure ]
